# Use a Python base image
FROM python:3.8-slim

# Install wget and other necessary tools
RUN apt-get update && apt-get install -y wget

# Install Quarto
RUN wget -q -O quarto.deb https://github.com/quarto-dev/quarto-cli/releases/download/v1.1.189/quarto-1.1.189-linux-amd64.deb
RUN dpkg -i quarto.deb

# Set the working directory in the container
WORKDIR /autograder

# Copy the necessary files into the container
COPY . /autograder

# Install Python dependencies
RUN pip install --upgrade pip
RUN pip install -r requirements.txt
RUN pip install -e .

# Command to run on container start
CMD ["python", "quartoquest/autograder.py"]
