name: QMD Autograder
on: [push]
jobs:
  check-repository-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: python repo_structure_check.py

  render-qmd:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install .
      - run: pip install -r requirements.txt
      - run: python render_qmd.py
      - uses: actions/upload-artifact@v2
        with:
          name: rendered-html
          path: '**/*.html'

  run-other-autograder-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install -r requirements.txt
      - run: python autograder.py
