name: Jupyter Notebook Autograder
on: [push]

jobs:
  check-repository-structure:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install --upgrade pip
      - run: pip install -e .
      - run: python -m jupyterquest.repo_structure_check

  run-autograder-tasks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - run: pip install --upgrade pip
      - run: pip install -e .
      - name: Check Code Style
        run: python -m jupyterquest.code_style_check
      - name: Assess Code Quality
        run: python -m jupyterquest.code_quality_check
      - name: Analyze Commit Messages
        run: python -m jupyterquest.commit_analysis
      - name: Run Autograder
        run: python -m jupyterquest.autograder
