name: CI/CD Pipeline

on:
  release:
    types: ["published"]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests and generate coverage report
        run: |
          pip install pytest coverage
          coverage run -m pytest
          coverage xml

      - name: Upload coverage to artifact
        uses: actions/upload-artifact@v2
        with:
          name: coverage-report
          path: coverage.xml

  publish:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Build package
        run: |
          python -m pip install --upgrade pip build
          python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_KEY }}

  codecov:
    needs: tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2

      - name: Download coverage report
        uses: actions/download-artifact@v2
        with:
          name: coverage-report
          path: . # Downloads the artifact to the root directory

      - name: Upload coverage report to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: coverage.xml
          fail_ci_if_error: true
