name: Python Tests

# Trigger on push and pull request events
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt  # Install from requirements.txt unconditionally
          pip install -e .  # Install QuartoQuest in editable mode
      - name: Run tests
        run: pytest tests/
